stages:
  - cloc_report
  - deploy

generate_cloc_report:
  stage: cloc_report
  image: python:3.12-slim
  before_script:
    - apt-get update && apt-get install -y cloc jq curl
  script:
    - mkdir -p public
    - cloc . --exclude-dir=.git --json --out=cloc-report.json
    - bash generate_index.sh cloc-report.json public/index.html
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main
    - master