stages:
  - cloc_report
  - deploy_to_wiki


generate_cloc_report:
  stage: cloc_report
  image: python:3.12-slim
  before_script:
    - apt-get update && apt-get install -y cloc jq curl dos2unix
    - dos2unix generate_index.sh
  script:
    - mkdir -p out
    - cloc . --exclude-dir=.git --json --out=cloc-report.json
    - bash generate_index.sh cloc-report.json out/index.html
  artifacts:
    paths:
      - out
    expire_in: 1 week

wiki:
  stage: deploy_to_wiki
  image: alpine/git
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk add --no-cache bash
  script:
    - git clone https://oauth2:${CI_JOB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.wiki.git wiki
    - cp out/index.html wiki/cloc-report.html
    - cd wiki
    - git config user.email "gitlab-ci@example.com"
    - git config user.name "GitLab CI"
    - git add cloc-report.html
    - |
      if ! git diff --cached --quiet; then
        git commit -m "Update CLOC report [skip ci]"
        git push origin HEAD
      else
        echo "No changes to commit."
      fi
  only:
    - wiki