ai_review:
  stage: test
  image: python:3.10
  script:
    - pip install openai requests
    - python3 ai_review_bot.py
  only:
    - merge_requests
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    OPENAI_API_KEY: $OPENAI_API_KEY
