stages:
  - prepare
  - review

variables:
  MCP_PATH: "$CI_PROJECT_DIR/mcp/mcp.json"
  OPENAI_MODEL: "gpt-4o"
  OPENAI_API_BASE_URL: "https://api.openai.com/v1"
  OPENAI_SYSTEM_ROLE: "Ты помощник по code review. Проанализируй изменения."

prepare_mcp:
  stage: prepare
  image: alpine:latest
  script:
    - apk add --no-cache git
    - mkdir -p mcp
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - git diff origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"...HEAD > mcp/diff.patch
    - |
      cat > mcp/mcp.json <<EOF
      {
        "diff": "mcp/diff.patch"
      }
      EOF
  artifacts:
    paths:
      - mcp/
    expire_in: 1 hour
  only:
    - merge_requests



ai_review:
  stage: review
  image: docker.io/kremlsa/review-bot:latest
  script:
    - echo "🤖 Запуск анализа AI"
    - ls -la mcp
    - ls -la .
    - ls -la /
    
    # - /app/ai_review_bot --base-dir mcp
  dependencies:
    - prepare_mcp
  artifacts:
    paths:
      - mcp/ai_reply.md
    when: always
  only:
    - merge_requests


