stages:
  - review

variables:
  OPENAI_API_KEY: "$OPENAI_API_KEY"
  OPENAI_API_BASE_URL: "https://api.openai.com/v1"
  OPENAI_MODEL: "gpt-4o"
  OPENAI_SYSTEM_ROLE: "Ты помощник по code review. Проанализируй diff и предложи улучшения."
  MCP_PATH: "mcp/mcp.json"

ai_review:
  stage: review
  image: docker.io/kremlsa/review-bot:latest
  script:
    - echo "📦 Генерируем diff..."
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - git diff origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"...HEAD > mcp/diff.patch

    - echo "📝 Генерируем mcp.json"
    - mkdir -p mcp
    - |
      cat > mcp/mcp.json <<EOF
      {
        "diff": "mcp/diff.patch"
      }
      EOF

    - echo "🤖 Запуск AI бота"
    - /app/ai_review_bot
  only:
    - merge_requests
  artifacts:
    paths:
      - mcp/ai_reply.md
    when: always
